export const CAMPGROUNDS_FETCH = "CAMPGROUNDS_FETCH";
export const CAMPGROUNDS_SUCCESS = "CAMPGROUNDS_SUCCESS";
export const CAMPGROUNDS_FAILURE = "CAMPGROUNDS_FAILURE";

export const CLEAR_CAMPGROUND_ERRORS = "CLEAR_CAMPGROUND_ERRORS"