export const CAMPGROUNDS_FETCH = "CAMPGROUNDS_FETCH";
export const CAMPGROUNDS_SUCCESS = "CAMPGROUNDS_SUCCESS";
export const CAMPGROUNDS_FAILURE = "CAMPGROUNDS_FAILURE";

export const CAMPGROUND_BY_ID_FETCH = "CAMPGROUND_BY_ID_FETCH"
export const CAMPGROUND_BY_ID_SUCCESS = "CAMPGROUND_BY_ID_SUCCESS"
export const CAMPGROUND_BY_ID_FAILURE = "CAMPGROUND_BY_ID_FAILURE"